#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <lilv/lilv.h>
#include "md5.h"

// TODO: make objcopy executable configurable
#define OBJCOPY arm-none-eabi-objcopy

int md5(const char *s, char *hash) {
    MD5_CTX mdContext;
    unsigned int len = strlen(s);

    MD5Init (&mdContext);
    MD5Update (&mdContext, s, len);
    MD5Final (&mdContext);
    for (int i = 0; i < 16; i++) snprintf (hash + 2*i, 3, "%02x", mdContext.digest[i]);
    return 1;
}

typedef struct DescriptorListItem {
    char symbol[sizeof("lv2_descriptor_") + 32 + 1];
    struct DescriptorListItem* next;
} DescriptorListItem;


int main(int argc, char** argv) {
    // Alter plugin descriptor symbols to include the md5 hash of the plugin
    // URI, and write the result to a header a file so the host knows about a
    // descriptor for each plugin.
    // TODO: Compile the plugin's TTL files to blobs the host can use
 
    LilvWorld *world = lilv_world_new();
    lilv_world_load_all(world);
    const LilvPlugins* plugins = lilv_world_get_all_plugins(world);
    const LilvNode *n;
    char plugin_uri_md5[33];
    int descriptor_symbol_len = sizeof("lv2_descriptor_") + 32;
    char *cmd;
    const char *cmd_fmt = "arm-none-eabi-objcopy --redefine-sym lv2_descriptor=%s %s";
    const char *plugin_library_path;

    DescriptorListItem *cur, *next, *prev=NULL, *first=NULL;

    LILV_FOREACH(plugins, i, plugins) {
        LilvPlugin *plugin = (LilvPlugin *) ( lilv_plugins_get(plugins, i));
        n = lilv_plugin_get_uri(plugin);
        printf("%s\r\n", lilv_node_as_string(n));
        const char *plugin_uri = lilv_node_as_string(n);
        md5(plugin_uri, plugin_uri_md5);

        cur = malloc(sizeof(DescriptorListItem));
        cur->next = NULL;
        if (prev) prev->next = cur;
        else first = cur;

        snprintf(cur->symbol, descriptor_symbol_len + 1, "lv2_descriptor_%s", plugin_uri_md5);

        n = lilv_plugin_get_library_uri(plugin);
        plugin_library_path = lilv_uri_to_path(lilv_node_as_string(n));

        int cmd_len = strlen(cmd_fmt) + descriptor_symbol_len + strlen(plugin_library_path) - 4;
        cmd = malloc(cmd_len + 10);
        snprintf(cmd, cmd_len, cmd_fmt, cur->symbol, plugin_library_path);
        //printf("cmd=%s\r\n", cmd);
        
        if (system(cmd) == -1) {
            printf("Warning: failed to redefine symbol: %s\n", cmd);
        }
        free(cmd);
        prev = cur;
    }

    FILE *outfile = fopen("descriptors.h", "w");
    fprintf(outfile, "/* This file is automatically generated by staticizer.*/\n\n");

    for (cur=first;cur;cur=cur->next) {
        fprintf(outfile, "extern const LV2_Descriptor *%s(uint32_t index);\n", cur->symbol);
    }

    fprintf(outfile, "\nconst void* lv2_descriptor_loaders[] = {\n");
    for (cur=first;cur;cur=cur->next) {
        fprintf(outfile, "    %s,\n", cur->symbol);
    }
    fprintf(outfile, "    NULL\n};\n\n");

    for (cur=first;cur;) {
        next = cur->next;
        free(cur);
        cur = next;
    }

    fclose(outfile);

    lilv_world_free(world);
}
