#!/usr/bin/env python
import lilv
from hashlib import md5
import subprocess


def main():
    world = lilv.World()
    world.load_all()
    plugins = world.get_all_plugins()
    initial_plugin_list = []
    for plugin in plugins:
        uri = plugin.get_uri().as_string()
        path = lilv.lilv_uri_to_path(plugin.get_library_uri().as_string())
        initial_plugin_list.append({'uri': uri,
                                    'path': path,
                                    'symbol': "lv2_descriptor_%s" % md5(uri).hexdigest()})
    f = open("descriptors.h", "w")
    f.write("/* This file is automatically generated by staticizer.py*/\n\n")

    plugin_list = []
    for p in initial_plugin_list:
        try:
            subprocess.check_output(["arm-none-eabi-objcopy", "--redefine-sym", "lv2_descriptor=%s" % (p['symbol'],), p['path']], stderr=subprocess.STDOUT)
        except subprocess.CalledProcessError  as e:
            print "Failed to process %s (%d): %s" % (p['uri'], e.returncode, e.output)
            continue
        plugin_list.append(p)

    for p in plugin_list:
        f.write("extern const LV2_Descriptor *%s(uint32_t index);\n" % p['symbol'])

    f.write("\nconst void* lv2_descriptor_loaders[] = {\n")
    for p in plugin_list:
        f.write("    %s,\n" % p['symbol'])
        print p['uri']

    f.write("    NULL\n};\n\n")
    print "Done"


if __name__ == "__main__":
    main()
